-- Standard core tables (every zone). Do not fork.
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY, ts TEXT DEFAULT CURRENT_TIMESTAMP,
  actor TEXT, action TEXT, record_id INTEGER, detail TEXT);
CREATE TABLE IF NOT EXISTS attachments (id INTEGER PRIMARY KEY, record_id INTEGER, path TEXT);
CREATE TABLE IF NOT EXISTS config_versions (id INTEGER PRIMARY KEY, ts TEXT DEFAULT CURRENT_TIMESTAMP, key TEXT, value TEXT);
CREATE TABLE IF NOT EXISTS host_action_log (id INTEGER PRIMARY KEY, ts TEXT DEFAULT CURRENT_TIMESTAMP, action TEXT, result TEXT);
